### ISSUE TITLE
为什么我没有找到Stacked Sparse Autoencoder (sSAE)模型呀？

### ISSUE THREAD

**Issue by cug-auto-zp** [fuzimaoxinan/Pytorch-Deep-Neural-Networks#3]

**Comment by zhuofupan** [comment]
在AE里可以选 ae_type

**Comment by cug-auto-zp** [comment]
Thank you send E-mail to me.l am busy in studying .lf l read it,l will reply you  the first time.

**Comment by cug-auto-zp** [comment]
> 在AE里可以选 ae_type
好的非常感谢您的回复，我看看
